// A list of all actions in the system.
import { createTypes } from 'reduxsauce';

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  NOTIFICATION

  STARTUP

  ADD_TRANSACTION_ATTEMPT
  ADD_TRANSACTION_SUCCESS
  ADD_TRANSACTION_FAILURE

  GET_TRANSACTIONS_ATTEMPT
  GET_TRANSACTIONS_SUCCESS
  GET_TRANSACTIONS_FAILURE

  DELETE_TRANSACTION_ATTEMPT
  DELETE_TRANSACTION_SUCCESS
  DELETE_TRANSACTION_FAILURE

  STORE_LOADED
`);
